### Numpy Praction Session of Day 7

In [ ]:
# Pip install numpy

In [1]:
# Import this library in j.notebook
import numpy as np

### Creating an array using numpy library

In [2]:
food=np.array(["Chicken","Bryani","Salad","Raita"])
food

array(['Chicken', 'Bryani', 'Salad', 'Raita'], dtype='<U7')

In [4]:
price=np.array([50,150,30,20])
price

array([ 50, 150,  30,  20])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

4

In [8]:
len(food)

4

In [9]:
price[3]

20

In [10]:
price[0:]

array([ 50, 150,  30,  20])

In [11]:
food[2]

'Salad'

In [13]:
price.mean()

62.5

In [15]:
# Zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
# Ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
# Empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [20]:
# arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# specify
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Specific Interval
np.arange(2,10,2)

array([2, 4, 6, 8])

In [26]:
# Table
np.arange(4,44,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [28]:
# Line space
np.linspace(1,80,num=8)

array([ 1.        , 12.28571429, 23.57142857, 34.85714286, 46.14285714,
       57.42857143, 68.71428571, 80.        ])

In [29]:
# Specify data type
np.ones(40, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
# Specify data type
np.ones(40, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

### Array functions

In [32]:
a=np.array([2,1,10,5,3.2,8,12,20,10.5,16,18])
a

array([ 2. ,  1. , 10. ,  5. ,  3.2,  8. , 12. , 20. , 10.5, 16. , 18. ])

In [34]:
a.sort()
a

array([ 1. ,  2. ,  3.2,  5. ,  8. , 10. , 10.5, 12. , 16. , 18. , 20. ])

In [35]:
b=np.array([2,10,5,3.5,20,14,16,30,25,18,40,35,32.6])
b

array([ 2. , 10. ,  5. ,  3.5, 20. , 14. , 16. , 30. , 25. , 18. , 40. ,
       35. , 32.6])

In [36]:
c=np.concatenate((a,b))
c

array([ 1. ,  2. ,  3.2,  5. ,  8. , 10. , 10.5, 12. , 16. , 18. , 20. ,
        2. , 10. ,  5. ,  3.5, 20. , 14. , 16. , 30. , 25. , 18. , 40. ,
       35. , 32.6])

In [37]:
c.sort()
c

array([ 1. ,  2. ,  2. ,  3.2,  3.5,  5. ,  5. ,  8. , 10. , 10. , 10.5,
       12. , 14. , 16. , 16. , 18. , 18. , 20. , 20. , 25. , 30. , 32.6,
       35. , 40. ])

### 2-D Arrays

In [43]:
a=np.array([[1,2,3], [3,2,1]])
a

array([[1, 2, 3],
       [3, 2, 1]])

In [44]:
b=np.array([[2,3,1],[3,1,2]])
b

array([[2, 3, 1],
       [3, 1, 2]])

In [46]:
c=np.concatenate((a,b), axis=0)
c

array([[1, 2, 3],
       [3, 2, 1],
       [2, 3, 1],
       [3, 1, 2]])

In [49]:
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 2, 3, 1],
       [3, 2, 1, 3, 1, 2]])

### Array Example

In [52]:
Code=np.array([[[0,1,2,3],[4,5,6,7]],
               [[0,1,2,3],[4,5,6,7]],
               [[0,1,2,3],[4,5,6,7]]])
Code

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [59]:
type(Code)

numpy.ndarray

In [55]:
# to find dimension number
Code.ndim

3

In [57]:
b=np.array([[5,6,7],[8,9,10],[10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [58]:
b.ndim

2

In [61]:
#Number of ELements
Code.size

24

In [63]:
Code

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [62]:
Code.shape

(3, 2, 4)

In [66]:
# 3*3 
a=np.arange(9)   
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
# Reshape
# 3*3=9
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
#reshape
np.reshape(a,newshape=(1,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [70]:
# Convert 1-D Into 2-D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a.shape

(9,)

In [74]:
# Row wise 2D conversion
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [75]:
b.shape

(1, 9)

In [77]:
# Coloum wise 2D conversion
c=a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [79]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [82]:
a*4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [83]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
a.sum()

45

In [85]:
a.mean()

5.0