In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [4]:
a2.shape

(1, 6)

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(a[0])

[1 2 3 4]


In [7]:
print(a[1])

[5 6 7 8]


In [8]:
print(a[2])

[ 9 10 11 12]


### Adding, removing, and sorting elements
- This section covers np.sort(), np.concatenate()

In [11]:
a1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
a1

array([2, 1, 5, 3, 7, 4, 6, 8])

In [12]:
np.sort(a1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
a2 = np.array([1, 2, 3, 4])
a2

array([1, 2, 3, 4])

In [14]:
b1 = np.array([5, 6, 7, 8])
b1

array([5, 6, 7, 8])

In [15]:
np.concatenate((a2, b1))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [17]:
y = np.array([[5, 6]])
y

array([[5, 6]])

In [19]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a2 = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
a2

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [22]:
a2.ndim

3

In [23]:
a2.size

24

In [24]:
a2.shape

(3, 2, 4)

In [25]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [26]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [29]:
a.shape

(6,)

In [30]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [31]:
a2.shape

(1, 6)

In [32]:
row_vector = a[np.newaxis, :]
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [33]:
row_vector.shape

(1, 6)

In [34]:
col_vector = a[:, np.newaxis]
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [35]:
col_vector.shape

(6, 1)

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [37]:
a.shape

(6,)

In [38]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
b.shape

(6, 1)

In [40]:
c = np.expand_dims(a, axis=0)
c

array([[1, 2, 3, 4, 5, 6]])

In [41]:
c.shape

(1, 6)

### Indexing and slicing

In [42]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [43]:
data[1]

2

In [44]:
data[0:2]

array([1, 2])

In [45]:
data[1:]

array([2, 3])

In [46]:
data[-2:]

array([2, 3])

In [47]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
print(a[a < 5])

[1 2 3 4]


In [49]:
five_up = (a >= 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [51]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [53]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [57]:
list_of_coordinates= list(zip(b[0], b[1]))

for c in list_of_coordinates:
    print(c)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [58]:
(a[b])

array([1, 2, 3, 4])

In [59]:
not_there = np.nonzero(a == 42)
not_there

(array([], dtype=int64), array([], dtype=int64))

### How to create an array from existing data

In [60]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
a1 = a[3:8]
a1

array([4, 5, 6, 7, 8])

In [62]:
a1 = np.array([[1, 1],
               [2, 2]])
a1

array([[1, 1],
       [2, 2]])

In [63]:
a2 = np.array([[3, 3],
               [4, 4]])
a2

array([[3, 3],
       [4, 4]])

In [64]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [65]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [66]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [67]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [68]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [69]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [72]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [73]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations
- This section covers addition, subtraction, multiplication, division, and more

In [75]:
data = np.array([1, 2])
data

array([1, 2])

In [76]:
ones = np.ones(2, dtype=int)
ones

array([1, 1])

In [77]:
data + ones

array([2, 3])

In [78]:
data - ones

array([0, 1])

In [79]:
data * data

array([1, 4])

In [80]:
data / data

array([1., 1.])

In [81]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [82]:
a.sum()

10

In [83]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [84]:
b.sum(axis=0)

array([3, 3])

In [85]:
b.sum(axis=1)

array([2, 4])

### Broadcasting

In [86]:
data = np.array([1.0, 2.0])
data

array([1., 2.])

In [87]:
data * 1.6

array([1.6, 3.2])

### More useful array operations

In [88]:
data.max()

2.0

In [89]:
data.min()

1.0

In [90]:
data.sum()

3.0

In [91]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [92]:
a.sum()

4.8595784

In [93]:
a.min()

0.05093587

In [94]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

### Creating matrices

In [95]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
data[0, 1]

2

In [97]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [98]:
data[0:2, 0]

array([1, 3])

In [99]:
data.max()

6

In [100]:
data.min()

1

In [101]:
data.sum()

21

In [102]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [103]:
data.max(axis=0)

array([5, 6])

In [104]:
data.max(axis=1)

array([2, 5, 6])

In [105]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [106]:
ones = np.array([[1, 1], [1, 1]])
ones

array([[1, 1],
       [1, 1]])

In [107]:
data + ones

array([[2, 3],
       [4, 5]])

In [108]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
ones_row = np.array([[1, 1]])
ones_row

array([[1, 1]])

In [110]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [111]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [112]:
np.ones(3)

array([1., 1., 1.])

In [113]:
np.zeros(3)

array([0., 0., 0.])

In [114]:
# the simplest way to generate random numbers
rng = np.random.default_rng(0)
rng

Generator(PCG64) at 0x17CE0E69C80

In [115]:
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [116]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [117]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [118]:
rng.random((3, 2))

array([[0.01652764, 0.81327024],
       [0.91275558, 0.60663578],
       [0.72949656, 0.54362499]])

### Generating random numbers

In [119]:
rng.integers(5, size=(2, 4))

array([[2, 4, 1, 4],
       [3, 0, 1, 4]], dtype=int64)

### How to get unique items and counts

In [120]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [121]:
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [123]:
unique_values, indices_list = np.unique(a, return_index=True)
indices_list

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64)

In [124]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
occurrence_count

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64)

In [125]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [126]:
unique_values = np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [127]:
unique_rows = np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [129]:
indices

array([0, 1, 2], dtype=int64)

In [130]:
occurrence_count

array([2, 1, 1], dtype=int64)

### Transposing and reshaping a matrix

In [131]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [133]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [134]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [135]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array

In [136]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [138]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [139]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [141]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
reversed_arr_columns

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [142]:
arr_2d[1] = np.flip(arr_2d[1])
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [143]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

### Reshaping and flattening multidimensional arrays

In [144]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [145]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [149]:
a1 = x.flatten()
a1[0] = 99

In [150]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
a2 = x.ravel()
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [153]:
a2[0] = 98
x

array([[98,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [154]:
a2

array([98,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### How to access the docstring for more information

In [155]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [158]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

### Working with mathematical formulas

### How to save and load NumPy objects

In [161]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [162]:
np.save('filename', a)

In [164]:
b = np.load('filename.npy')
b

array([1, 2, 3, 4, 5, 6])

In [165]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [166]:
np.savetxt('new_file.csv', csv_arr)

In [167]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])