In [1]:
import numpy as np

In [2]:
a=np.array([[5,5,5],[5,5,5],[5,5,5],])
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
b=np.zeros([4])
b

array([0., 0., 0., 0.])

In [6]:
c=np.ones([4])
c

array([1., 1., 1., 1.])

In [8]:
d=np.empty([3])
d

array([1.41590934e+195, 9.34609790e-307, 1.50196730e-307])

In [10]:
e=np.arange(7)
e

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
f=np.arange(1,20)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
g=np.arange(1,20,3)
g

array([ 1,  4,  7, 10, 13, 16, 19])

In [20]:
h=np.linspace(1,15,num=5)
h

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [22]:
i=np.ones(4,dtype=np.int8)
i

array([1, 1, 1, 1], dtype=int8)

In [23]:
j=np.ones(6,dtype=np.float64)
j

array([1., 1., 1., 1., 1., 1.])

In [25]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.empty((5,6))

array([[1.14235523e-311, 1.01283457e-321, 0.00000000e+000,
        0.00000000e+000, 1.29056457e-306, 5.02034658e+175],
       [2.14394219e+160, 8.38309466e+165, 3.89190079e-033,
        2.21540056e+160, 2.59027859e-144, 3.80985069e+180],
       [1.14428494e+243, 2.59027907e-144, 7.79952704e-143,
        1.60339525e-051, 2.59983814e-056, 1.25759362e-047],
       [5.40032667e-062, 4.99874559e+217, 5.49419094e-143,
        2.91237123e+257, 5.56111702e+180, 5.74015544e+180],
       [1.94919988e-153, 2.59027858e-144, 2.59903818e-144,
        5.27365184e-091, 1.79862019e-052, 1.17740838e-047]])

In [38]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])